"use client";

import { useState } from "react";
import type { Quote } from "../../lib/shayari";

type QuoteGridProps = {
  quotes: Quote[];
  languageLabel?: string;
};

export function QuoteGrid({ quotes, languageLabel }: QuoteGridProps) {
  const [feedback, setFeedback] = useState<Record<string, string>>({});

  const flash = (id: string, message: string) => {
    setFeedback((current) => ({ ...current, [id]: message }));
    window.setTimeout(
      () => setFeedback((current) => ({ ...current, [id]: "" })),
      1800,
    );
  };

  const writeToClipboard = async (value: string) => {
    try {
      if (navigator.clipboard?.writeText) {
        await navigator.clipboard.writeText(value);
        return true;
      }
    } catch {
      // Fall through to the legacy browser-safe copy path.
    }

    const textarea = document.createElement("textarea");
    textarea.value = value;
    textarea.setAttribute("readonly", "");
    textarea.style.position = "fixed";
    textarea.style.opacity = "0";
    document.body.appendChild(textarea);
    textarea.select();
    const copied = document.execCommand("copy");
    textarea.remove();
    return copied;
  };

  const copyQuote = async (quote: Quote) => {
    const copied = await writeToClipboard(quote.text);
    flash(quote.id, copied ? "Copied" : "Copy unavailable");
  };

  const shareQuote = async (quote: Quote) => {
    const url = `${window.location.origin}${window.location.pathname}#${quote.id}`;
    if (navigator.share) {
      try {
        await navigator.share({ text: quote.text, url });
        flash(quote.id, "Shared");
        return;
      } catch (error) {
        if (error instanceof DOMException && error.name === "AbortError") return;
      }
    }
    const copied = await writeToClipboard(`${quote.text}\n${url}`);
    flash(quote.id, copied ? "Link copied" : "Share unavailable");
  };

  return (
    <div className="quote-grid" aria-label={`${quotes.length} shayari image cards`}>
      {quotes.map((quote, position) => (
        <article className="quote-card" id={quote.id} key={quote.id}>
          <figure className="quote-art">
            {/* SVG cards are generated by this site, so a direct img avoids an unnecessary optimizer round trip. */}
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              alt={`${languageLabel ?? quote.language} ${quote.emotion} quote image ${position + 1}`}
              decoding="async"
              height={1350}
              loading={position < 2 ? "eager" : "lazy"}
              src={quote.imageUrl}
              width={1080}
            />
          </figure>

          <div className="quote-card-body">
            <div className="quote-number">{String(position + 1).padStart(2, "0")}</div>
            <blockquote lang={quote.language === "hindi" ? "hi" : quote.language === "punjabi" ? "pa" : "en"}>
              {quote.text}
            </blockquote>

            <div className="meaning-box">
              <span>Meaning</span>
              <p>{quote.explanation}</p>
            </div>

            <div className="quote-actions" aria-label="Quote actions">
              <button onClick={() => copyQuote(quote)} type="button">
                <span aria-hidden="true">⧉</span> Copy
              </button>
              <a
                download={`${quote.language}-${quote.emotion}-${quote.index}.svg`}
                href={quote.imageUrl}
              >
                <span aria-hidden="true">↓</span> Image
              </a>
              <button onClick={() => shareQuote(quote)} type="button">
                <span aria-hidden="true">↗</span> Share
              </button>
              <span aria-live="polite" className="action-feedback">
                {feedback[quote.id]}
              </span>
            </div>
          </div>
        </article>
      ))}
    </div>
  );
}
